project:
  type: website
  output-dir: "docs"
  
website:
  title: "Shun Yamaya"
  favicon: figs/favicon.png
  navbar:
    left:
      - icon: github
        href: https://github.com/shunyamaya
      - text: "About"
        href: about.html
      
    background: "#E6E8E6"
    foreground: "#9F353A"
    # "#C63527"
  page-footer: 
    # center: 
    #   - "<p> Last updated <script> </script> </p>"
    background: "#E6E8E6"
    foreground: "#EACDC2"
  site-url: https://shunyamaya.github.io
  description: "Shun Yamaya's Personal Website"
  google-analytics: "G-J1H8HWS99H"

format:
  html:
    theme: default
    css: styles.css
    toc: false
    mainfont: Georgia, serif
    fontsize: 16px
    backgroundcolor: "#F9FAFB"
    linkcolor: "#B3555D"
    grid: 
      body-width: 800px

resources:
  - CNAME


