project:
  type: website
  output-dir: "docs"
  
website:
  title: "Shun Yamaya"
  favicon: figs/favicon.png
  navbar:
    right:
      - text: "About"
        href: about.html
      - icon: github
        href: https://github.com/shunyamaya
    background: "#FFFFFF"
    foreground: "#C63527"
  page-footer: 
    center: 
      - "<p>Copyright &copy; <script>document.write(new Date().getFullYear())</script> Shun Yamaya </p>"
    background: "#FFFFFF"
    foreground: "#EBCB64"
  site-url: https://shunyamaya.github.io
  description: "Shun's Personal Website"

format:
  html:
    theme: default
    css: styles.css
    toc: true



